### ISSUE TITLE
Footer: Project Scope did not mention what SEO footer option to use.  Implemented SEO footer was incorrect as well. For the standard SEO footer, It should be one of the given footer option in the list.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#1]
Here's the reference link:
https://knowledgebase.titanweb.com.au/development/updating-the-footer-for-seo-ranking

![image](https://cloud.githubusercontent.com/assets/12888048/9712295/435b194e-557c-11e5-8fe2-73bf35e129e5.png)

**Comment by ramoncebudigital** [comment]
Project scope has been updated.

**Comment by romatitan** [comment]
titanweb logo was also included inside the <a> tag.
Only the "Titan Web" text should be the link text.

Reference Link:
https://knowledgebase.titanweb.com.au/development/updating-the-footer-for-seo-ranking
