### ISSUE TITLE
Homepage: "Why Choose Us" headline used h1. It should be h2.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#10]
![image](https://cloud.githubusercontent.com/assets/12888048/9724006/f335b54c-5601-11e5-8de5-3f71597167a0.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9724007/002c0544-5602-11e5-82f6-b13b53cfd6c5.png)

**Comment by ramoncebudigital** [comment]
Clearly this is invalid.
![screenshot_3](https://cloud.githubusercontent.com/assets/11186436/9751781/83b45f90-56db-11e5-8e4c-46265d042447.png)
