### ISSUE TITLE
Clarification: Should the featured services on sidebar use a permalink or page link? If permalink, what particular page should it be linked? Does the services page title is needed to use permalink as well?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#15]
Please clarify with leads and update the scope accordingly.

![image](https://cloud.githubusercontent.com/assets/12888048/9724688/33d4c12c-560e-11e5-8bbb-a11f1a06ff9c.png)

**Comment by ramoncebudigital** [comment]
when you click the link, it will go to the services post in the same page.

**Comment by romatitan** [comment]
Anchor link was used.
