### ISSUE TITLE
Services: The post title should have (allow) up to 2 lines only

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#16]
Reference Link:
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/post-title-and-post-desription

![image](https://cloud.githubusercontent.com/assets/12888048/9724732/03e6a77c-560f-11e5-87fb-dd8943cce796.png)

**Comment by ramoncebudigital** [comment]
This shouldn't be 2 lines, because this doesn't have single page.

**Comment by romatitan** [comment]
In the project scope, featured services on sidebar will use permalink or pagelink. #15 
And now it was updated to  "ourservices display 4 on click will go to its respective title" anchor link.
