### ISSUE TITLE
Gallery: Pagination wasn't implemented. It should have pagination after 9 images

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#18]
Always follow the number of items to display per page based from the design, except if design shows less than 4 items. This is regardless if design shows a pagination or not.

Reference Link:
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/pagination-links

![image](https://cloud.githubusercontent.com/assets/12888048/9724927/350823ec-5611-11e5-862a-2d796628dcc9.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

Infinite pagination is applied to all page.

Thanks,
Christian

**Comment by romatitan** [comment]
Hi Christian,

This is not invalid.
You should at least stated it in the project scope to use 'infinite scroll pagination' instead of 'pagination' alone.

Reference #30
