### ISSUE TITLE
News: Pagination wasn't implemented. It should paginate if more than 4 items as stated in the project scope.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#21]
![image](https://cloud.githubusercontent.com/assets/12888048/9725111/ca1fa17e-5613-11e5-8a73-4a798c775713.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

Infinete scroll pagination is used in the site.

Thanks,
Christian
