### ISSUE TITLE
All Designs: Infinite scroll was used. It should paginate if more than 12 items as stated in the project scope

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#30]
![image](https://cloud.githubusercontent.com/assets/12888048/9725716/300b5de6-561b-11e5-89c1-a0351df2e402.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9725688/c05795dc-561a-11e5-8d93-656f797410fc.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9729709/d3883eee-5643-11e5-9ddc-007b0472de39.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

paginate Infinite scroll is applied, to the pagination, so when you reach to the bottom of the products, with more than 12 it'll load significantly, which in case you will not feel the pagination, because the loading time is fast, let me know you thoughts on this issue.

Thanks,
Christian

**Comment by romatitan** [comment]
Hi Christian,

This is not invalid.
You should at least stated it in the project scope to use 'infinite scroll pagination' instead of 'pagination' alone.

![image](https://cloud.githubusercontent.com/assets/12888048/9983743/9eee4cee-603b-11e5-8087-f57ed0e3d2b9.png)
