### ISSUE TITLE
Browse Products: Incorrect filter result - 1. Block Width = true/ have selected value 2. Price Range = true/have selected value.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#36]
Filter Result: Different block width, same price range.
It should be same block width and price range.

Step to Replicate
1. Block Width = true/ have selected value
2. Price Range = true/have selected value
3. Click Search button.

![image](https://cloud.githubusercontent.com/assets/12888048/9726154/bbe0a2e4-5621-11e5-8591-5100c0e71343.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

This is not a bug, the search Browse Houses Functionalityis not strict, it will search all selected values based on the selected values, this is an OR statement when searching query, please based on PS 
[ https://docs.google.com/spreadsheets/d/1InKW5r1ulGQLfEC7SuOPJ2ZMWe7L2mS_aCAMHo-MIMA/edit?usp=sharing  ]

Thanks,
Christian
