### ISSUE TITLE
All Designs Single - Sidebar: Misleading text. It seems to have a function to link, but it doesn't work.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#37]
![image](https://cloud.githubusercontent.com/assets/12888048/9726938/cc339a3e-562b-11e5-9961-1c1284e9dfbc.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

I've updated, the project scope, this are labelled acf found on products.

Thanks,
Christian

**Comment by romatitan** [comment]
It's a dead link.
What will be its role?

![image](https://cloud.githubusercontent.com/assets/12888048/9871945/8a03de2e-5bc8-11e5-9b43-76f478455b20.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9871950/8e60a240-5bc8-11e5-9b5f-4ea39f42ba17.png)

**Comment by christiancebudigital** [comment]
Hi Roma, 

I think the client, will provide the link, since this is an approved design, they can provide link or not.

Thanks,
Christian

**Comment by romatitan** [comment]
Hi Christian,

Kindly clarify this with the project manager of this project.

Thanks.

**Comment by christiancebudigital** [comment]
Hi Roma,

Ive send out my queries with the pm, still waiting on their feedback, anyways this is already dynamic, they can just provide the link or not.

Thanks,
Christian

**Comment by christiancebudigital** [comment]
According to  Franceso this will go to Contact us page for enquiries
