### ISSUE TITLE
All Designs Single: Banner was too large. Banner on inner pages should have its size reduced

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#40]
![image](https://cloud.githubusercontent.com/assets/12888048/9728161/bb53c36c-5638-11e5-85b8-76054bce7957.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

Based on the approved design, banner is not reduced, it is on full height. see attached image.

![09-hom-home-designs-single](https://cloud.githubusercontent.com/assets/11186331/9782494/0ed5a2e2-57d0-11e5-835c-f92185e1fe71.jpg)

Thanks,
Christian

**Comment by romatitan** [comment]
Conflict information given.
As per the project scope stated, all inner pages should reduced the banner sizes.
![image](https://cloud.githubusercontent.com/assets/12888048/9872069/7bd9b52a-5bc9-11e5-922d-4b40cf1351aa.png)
