### ISSUE TITLE
Admin:  E-mail address used in general settings was different from the user account e-mail

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#47]
![image](https://cloud.githubusercontent.com/assets/12888048/9729149/e5dd8d82-563f-11e5-99d2-8003c85bf3e2.png)

**Comment by christiancebudigital** [comment]
Hi All,

updated the user accoung e-mail.

Thanks,
Christian

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9872340/55cf1dfa-5bcb-11e5-9c4f-a47042b861c4.png)
