### ISSUE TITLE
Clarification - Why Choose Us: Why does the wysiwyg acf  used was different from the normal wysiwyg editor? It has no visual option as well.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#50]
![image](https://cloud.githubusercontent.com/assets/12888048/9730698/db9cc0a8-564a-11e5-9bac-34661ba67c2b.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9730699/dde4430e-564a-11e5-9700-f2d1aca90c07.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

It is because this is a plugin by acf, visual text is restricted on the wysywg acf, it is also because some content that is not required in the field, and some field have specific option in acf, hope i have answered your question.

Thanks,
Christian

**Comment by romatitan** [comment]
What do you mean by "visual text is restricted on the wysiwyg acf?

**Comment by christiancebudigital** [comment]
Hi roma,

My bad, acf is already to date, did'nt notice, that they have added tab which can add visual and text.

Thanks,
Christian
