### ISSUE TITLE
All Design Single - iPodtouch5: Horizontal scrolling

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#58]

**Comment by christiancebudigital** [comment]
Hi Roma,

Please provide screenshot?.. as we cant replicate it on our side, since we don't have iPod touch here...

Thanks,
Christian

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9984206/3ddeaccc-6046-11e5-9276-c373f1402092.png)
