### ISSUE TITLE
Clarification: In the given design it has two phone numbers displayed in the header. Should we include another phone number in the header?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#63]
![image](https://cloud.githubusercontent.com/assets/12888048/9984356/78eb0a02-6048-11e5-8d56-9f3a07510505.png)

**Comment by christiancebudigital** [comment]
Hi roma,

Ive added a new phone number 2 in business details.

Thanks,
Christian
