### ISSUE TITLE
General: The infinite scroll pagination was enabled even it has not yet hit the bottom of the main content, thus affects the user experience while scrolling down and reading the content of the page.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#64]
Affected page(s): 
Pages which have infinite scroll pagination

**Comment by christiancebudigital** [comment]
Hi Roma,

This is the functionality of infinite scrolling, it first load all content of the post, and then calls data when reached at the bottom of the page, try loading the page first, when all data is loaded try scrolling at the bottom of the page, when reached at the bottom of the page, you will then see a loading icon that triggers the next data to be displayed in the page, hopefully this clears things out, let me know your thoughts.

Thanks,
Christian

**Comment by romatitan** [comment]
Hi Christian,

When you go to the page with infinite scroll, try to scroll down just a little then observe the page.
It seems that the page move to top, but it happens because the infinite scroll was already triggered and load the next data even it has not yet hit the bottom of the page.

Kindly refer to this site.
Reference: http://greenstarelectricalservices.stage.titanweb.com.au/news/
