### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#69]
![image](https://cloud.githubusercontent.com/assets/12888048/10153073/2823b65c-668b-11e5-95ca-266209942383.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

Favicon is working on our end, see attached file.
![icon](https://cloud.githubusercontent.com/assets/11186331/10154818/be9b772e-669e-11e5-9db8-6890a514de44.jpg)

Thanks,
Christian
