### ISSUE TITLE
Clarification - Banner: "Find out more" permalink should be linked in what particular page? It is not mentioned in the project scope.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#7]
![image](https://cloud.githubusercontent.com/assets/12888048/9712996/2088ac88-5581-11e5-8d4e-be067a3d8b13.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9712999/2285140e-5581-11e5-8a59-1deb4cbc0abf.png)

**Comment by ramoncebudigital** [comment]
This is a project scope error, this should be pagelink.

**Comment by romatitan** [comment]
Banner ACF was added and permalink changed to page link
![image](https://cloud.githubusercontent.com/assets/12888048/9869840/a9de8884-5bb9-11e5-9a98-9f65323e74cc.png)
