### ISSUE TITLE
News - S4 & iPodtouch5: Truncated text of a post with a long title.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#71]
![image](https://cloud.githubusercontent.com/assets/12888048/10154504/9285c486-669a-11e5-96dd-6a5bb528191e.png)

**Comment by romatitan** [comment]
Kindly check again with S4 and iPodtouch5 portrait view as well as in browser.

S4 & iPodtouch5
![image](https://cloud.githubusercontent.com/assets/12888048/10156381/04653394-66b3-11e5-81b3-a32700fcb35e.png)


browser
![image](https://cloud.githubusercontent.com/assets/12888048/10156349/a1cb520e-66b2-11e5-8534-098d803ff99a.png)

**Comment by romatitan** [comment]
Still reproducible on S4 and browser.

**Comment by christiancebudigital** [comment]
Hi Roma,

Please clear cache, as this is working on our end.

Thank,
Christian
![aa](https://cloud.githubusercontent.com/assets/11186331/10211370/297085a8-6825-11e5-8d40-b3154aadd0b6.jpg)
![bb](https://cloud.githubusercontent.com/assets/11186331/10211371/29760b7c-6825-11e5-902b-b93f0f309fa4.jpg)

**Comment by romatitan** [comment]
Still reproducible on S4 and iPad Air portrait view.

S4 
screenshot
![image](https://cloud.githubusercontent.com/assets/12888048/10237974/bc8515b8-68eb-11e5-8471-07e4015655d7.png)

Photo captured
![image](https://cloud.githubusercontent.com/assets/12888048/10237975/c36a6bda-68eb-11e5-8d2e-6fddd9168b38.png)

iPad Air
screenshot
![image](https://cloud.githubusercontent.com/assets/12888048/10237980/d1bb9fce-68eb-11e5-8b50-d04ff7e04ea3.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10237983/d58fbd4c-68eb-11e5-83d9-0ee24f9252ed.png)

**Comment by romatitan** [comment]
Still reproducible on s4 portrait view

**Comment by christiancebudigital** [comment]
please clear cache. thanks
![samsung](https://cloud.githubusercontent.com/assets/11186331/10271951/86947874-6b4b-11e5-9b78-825632b39986.jpg)

**Comment by romatitan** [comment]
Still reproducible on s4 portrait view

**Comment by romatitan** [comment]
Still reproducible on s4 and ipodtouch5 portrait & landscape view
