### ISSUE TITLE
All Design - Related Post - iPad Air: The product's featured image was stretched 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#76]
![image](https://cloud.githubusercontent.com/assets/12888048/10211309/84361684-6824-11e5-91b0-fb8e9d0317f0.png)

**Comment by romatitan** [comment]
Still reproducible in ipad air - portrait view.
And now with the browser as well.

**Comment by christiancebudigital** [comment]
Hi Roma,

Heres the attached image. of our ipad.
![image 1](https://cloud.githubusercontent.com/assets/11186331/10332544/84dd620e-6d10-11e5-9a36-1932c571e1ac.jpg)
![image](https://cloud.githubusercontent.com/assets/11186331/10332545/84e7de1e-6d10-11e5-8757-2c747ef631ed.jpg)

Thanks

**Comment by romatitan** [comment]
Hi Christian,
Kindly check the All Design single page > Relate Post (Other Houses You May Like)

Thanks.

**Comment by romatitan** [comment]
Fixed on iPad Air portrait view, however, it is reproducible on landscape view
